version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  web:
    image: apotdevin/thunderhub:v0.12.0
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 5m
    ports:
      - "$APP_THUNDERHUB_PORT:$APP_THUNDERHUB_PORT"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
      NO_VERSION_CHECK: "true"
      LOG_LEVEL: "debug"
      ACCOUNT_CONFIG_PATH: "/data/thubConfig.yaml"
    networks:
      default:
        ipv4_address: $APP_THUNDERHUB_IP
